name: stockmaster
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icons_plus: ^4.0.0
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  flutter_native_splash: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/banner1.png
    - assets/images/stockmaster.png
    - assets/icons/button_icon.png
    - assets/icons/icon.png
    - assets/icons/vetor_icon.png

flutter_native_splash:
  color: "#282828"
  image: assets/images/stockmaster.png
  android: true
  ios: true

