// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVboYm5DJTXJjjoILj9lvULibVA4mIScM',
    appId: '1:898428059117:web:22f16ef49520bb634f7be4',
    messagingSenderId: '898428059117',
    projectId: 'stockmaster-de428',
    authDomain: 'stockmaster-de428.firebaseapp.com',
    storageBucket: 'stockmaster-de428.appspot.com',
    measurementId: 'G-TNYSSR2XCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7gqG2onUZPtx5-m-Un1-ww3Gitz3dNiE',
    appId: '1:898428059117:android:509554b5516bdb404f7be4',
    messagingSenderId: '898428059117',
    projectId: 'stockmaster-de428',
    storageBucket: 'stockmaster-de428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALeLzRydIqyVOaccphlPp7Nk6JEh0GLVM',
    appId: '1:898428059117:ios:ca4e9892c239d0854f7be4',
    messagingSenderId: '898428059117',
    projectId: 'stockmaster-de428',
    storageBucket: 'stockmaster-de428.appspot.com',
    iosBundleId: 'com.example.stockmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALeLzRydIqyVOaccphlPp7Nk6JEh0GLVM',
    appId: '1:898428059117:ios:bf3b621f913afc8f4f7be4',
    messagingSenderId: '898428059117',
    projectId: 'stockmaster-de428',
    storageBucket: 'stockmaster-de428.appspot.com',
    iosBundleId: 'com.example.stockmaster.RunnerTests',
  );
}
